# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'joshua@github'
tagline:             '~/Documents &Gt;'
description:         'A simple blog on projects, software and cool things&trade;.'
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Joshua McIntosh
